Phase2
Star-Academy/Summer1400-FE-Team6 pull request #2
Opened 2021-07-29 16:54 UTC by methusaleh

2021-07-29 18:16 UTC, BijanEisapour requested changes
<p dir='rtl' align='right'>
بعضی از موارد خیلی جاها دیده شد ولی فقط یه کامنت گذاشتم
<br>
لطفاً همه رو اصلاح کنید

2021-07-29 18:16 UTC, BijanEisapour commented on .idea/Summer1400-FE-Team6.iml
>  </module>
<p dir='rtl' align='right'>
فایل‌های مربوط به IDE رو بذارد تو gitignore

2021-07-29 18:16 UTC, BijanEisapour commented on Style/scss/index.scss
> +  //background-image: url('assets/pic/bg.jpg');
<p dir='rtl' align='right'>
کامنت اضافی پاک شه

2021-07-29 18:16 UTC, BijanEisapour commented on Style/scss/index.scss
> +    border-radius: 10px;
<p dir='rtl' align='right'>
از پیکسل تا جای ممکن استفاده نکنید. به جاش em یا rem بذارید

2021-07-29 18:16 UTC, BijanEisapour commented on Style/scss/index.scss
> +    border: 3px solid white;
<p dir='rtl' align='right'>
اینجا پیکسل مشکلی نداره

2021-07-29 18:16 UTC, BijanEisapour commented on Style/scss/index.scss
> +  cursor: pointer;
<p dir='rtl' align='right'>
به صورت پیشفرض خودش pointer ئه

2021-07-29 18:16 UTC, BijanEisapour commented on Style/scss/login.scss
> +}
<p dir='rtl' align='right'>
اینو بذارید تو global styles و همه جا ازش استفاده کنید

2021-07-29 18:16 UTC, BijanEisapour commented on Style/scss/login.scss
> +}
<p dir='rtl' align='right'>
اینا تکرارین. بهتره برن تو global styles
<br>
از direction استفاده نکنید، به جاش از dir تو تگ html استفاده کنید

2021-07-29 18:16 UTC, BijanEisapour commented on Style/scss/login.scss
> +  -webkit-transition-timing-function: ease-in-out;
<p dir='rtl' align='right'>
نیاز به vendor prefix نیست. همینجوری کار میکنه

2021-07-29 18:16 UTC, BijanEisapour commented on Style/scss/song.scss
> +  background-image: url("../../assets/pic/4205784.jpg");
<p dir='rtl' align='right'>
اسمی که واسه فایل‌های asset میذارید کاملاً گویا و قابل فهم باشه جوری که صرفاً با دیدن اسمش بشه فهمید محتواش چیه نه اینکه نیاز باشه حتماً فایل رو باز کرد

2021-07-29 18:16 UTC, BijanEisapour commented on index.html
> +    <title>Music</title>
<p dir='rtl' align='right'>
اگه سایت فارسیه پس title هم باید فارسی باشه

2021-07-29 18:16 UTC, BijanEisapour commented on index.html
> +    <img src="assets/pic/fav.png" class="logo" alt="logo" onclick="document.location='#'">
<p dir='rtl' align='right'>
به جای onclick کل عکس رو بذارید تو تگ a که کاربر اگه از Screen Reader استفاده میکرد بفهمه میتونه روش کلیک کنه

2021-07-29 18:16 UTC, BijanEisapour commented on index.html
> +            </svg>
<p dir='rtl' align='right'>
چرا indent این شکلیه؟ از prettier یا موارد مشابه استفاده کنید

2021-07-30 06:52 UTC, hessamasna commented on index.html
> +            </svg>
از فرمتر خود وب استور استفاده شده !

2021-07-30 12:19 UTC, BijanEisapour approved these changes

2021-07-30 12:32 UTC, merged